#!/bin/bash
# 02-sysctl-structural — verify Module 02 sysctl snippet structural invariants
#
# Checks (without running Anaconda):
#   - 3 sysctl files written (99-hardening, 99-audit-fixes, 99-userns)
#   - 99-hardening.conf has 101 security/privacy params with performance knobs
#     left to Fedora/kernel policy
#   - 99-audit-fixes.conf has oops_limit/warn_limit/panic
#   - 99-userns.conf has max_user_namespaces=256
#   - fs.binfmt_misc.status REMOVED (authoritative in M21)
#   - No IPv6 .all.disable_ipv6 (VPN killswitch compat)
#   - wildcard + default pattern for per-interface IPv6 RA hardening

set -euo pipefail
. "$(dirname "$0")/lib.sh"

PROJECT_ROOT="$(find_project_root)"
KS_FILE="$PROJECT_ROOT/kickstart/snippets/02-sysctl.ks"
BPF_RUNTIME_GATE="$PROJECT_ROOT/tests/pre-ship/02-unprivileged-bpf-runtime.sh"
SYSCTL_RUNTIME_GATE="$PROJECT_ROOT/tests/pre-ship/02-sysctl-runtime.sh"
SMOKE_GATE="$PROJECT_ROOT/tests/smoke/M02-sysctl-smoke.sh"

test_start "02-sysctl-structural"

assert_file_exists "$KS_FILE"
assert_grep_fixed '/etc/sysctl.d/98-privacy-network.conf → M07 forwarding policy' \
    "$KS_FILE" "load-order inventory includes reset-safe M07 forwarding policy"
assert_grep_fixed 'precede reset-sensitive M02' "$KS_FILE" \
    "load-order inventory preserves forwarding-before-hardening dependency"
assert_grep_fixed '/etc/sysctl.d/99-sysctl.conf' "$KS_FILE" \
    "load-order inventory includes Fedora compatibility symlink"
assert_grep_fixed '/etc/sysctl.d/99-wan-ipv6-off.conf' "$KS_FILE" \
    "load-order inventory includes firstboot-generated physical IPv6 policy"

# --- extract heredoc bodies -------------------------------------------------
TMPDIR="$(mktemp -d)"
trap 'rm -rf "$TMPDIR"' EXIT

extract_heredoc "$KS_FILE" "HARDENING_EOF" "$TMPDIR/hardening.conf" || _fail "hardening.conf heredoc extraction"
extract_heredoc "$KS_FILE" "AUDIT_EOF"     "$TMPDIR/audit-fixes.conf" || _fail "audit-fixes heredoc extraction"
extract_heredoc "$KS_FILE" "USERNS_EOF"    "$TMPDIR/userns.conf" || _fail "userns heredoc extraction"

assert_file_min_size "$TMPDIR/hardening.conf"   1024 "hardening.conf >1KB"
assert_file_min_size "$TMPDIR/audit-fixes.conf" 64   "audit-fixes.conf >64B"
assert_file_min_size "$TMPDIR/userns.conf"      32   "userns.conf >32B"

# --- compose-time closed postconditions -------------------------------------
assert_grep_fixed "stat -Lc '%u:%g:%a:%h'" "$KS_FILE" \
    "M02 verifies owner, mode and single-link regular-file metadata"
assert_grep_fixed 'restorecon -F "${M02_SYSCTL_FILES[@]}"' "$KS_FILE" \
    "M02 restores all three exact SELinux labels"
assert_grep_fixed 'matchpathcon -V "$path"' "$KS_FILE" \
    "M02 verifies each resulting SELinux label"
assert_grep_fixed 'sysctl --dry-run -p "$path"' "$KS_FILE" \
    "M02 parser-checks every generated drop-in without changing runtime state"
assert_not_grep_extended '^[[:space:]]*sysctl[[:space:]]+--system' "$KS_FILE" \
    "M02 compose never applies unrelated runtime sysctls"
assert_grep_fixed 'M02 directive cardinality drift' "$KS_FILE" \
    "M02 fails compose when any generated directive count drifts"
assert_grep_fixed 'grep -Fxc "$parser_call" "$TMP_POST"' "$SMOKE_GATE" \
    "M02 smoke replaces only the exact sandbox-incompatible parser call"
assert_grep_fixed 'sysctl --dry-run -p "$SANDBOX_DIR$config"' "$SMOKE_GATE" \
    "M02 smoke parser-checks all generated bytes in the initial net namespace"
assert_not_grep 'sysctl --ignore' "$SMOKE_GATE" \
    "M02 smoke never hides unknown kernel keys"

# --- 99-hardening.conf param count ------------------------------------------
# Pattern allows optional leading '-' (systemd-sysctl ignore-on-error prefix,
# applied to kernel.core_pattern as a defensive measure for
# Coredump Layer 3 in the 6-layer block).
hardening_count=$(grep -cE '^-?[a-z]+\.' "$TMPDIR/hardening.conf" 2>/dev/null || true)
hardening_count=${hardening_count:-0}
assert_eq "101" "$hardening_count" "99-hardening.conf has exactly 101 params"
assert_grep_fixed '# === Boot integrity: disable kexec image loading for this running boot ===' \
    "$TMPDIR/hardening.conf" "kexec ratchet is classified as boot integrity"
assert_grep_fixed '# === Fedora/kernel defaults explicit (portability, drift prevention) ===' \
    "$TMPDIR/hardening.conf" "vendor-default section is labelled precisely"
assert_grep_fixed '# === Intentional NoID Privacy surface reduction (not a Fedora vendor default) ===' \
    "$TMPDIR/hardening.conf" "deliberate NoID Privacy tightenings have a separate section"
assert_grep_fixed 'mainline-derived perf implementation currently treats 3 like 2' \
    "$TMPDIR/hardening.conf" "perf level 3 does not overclaim Fedora semantics"

tcp_header_line=$(grep -nFx '# === TCP Hardening ===' "$TMPDIR/hardening.conf" \
    | cut -d: -f1 || true)
kexec_header_line=$(grep -nFx \
    '# === Boot integrity: disable kexec image loading for this running boot ===' \
    "$TMPDIR/hardening.conf" | cut -d: -f1 || true)
kexec_value_line=$(grep -nEx 'kernel\.kexec_load_disabled[[:space:]]*=[[:space:]]*1' \
    "$TMPDIR/hardening.conf" | cut -d: -f1 || true)
if [ -n "$tcp_header_line" ] && [ -n "$kexec_header_line" ] \
   && [ -n "$kexec_value_line" ] \
   && [ "$tcp_header_line" -lt "$kexec_header_line" ] \
   && [ "$kexec_header_line" -lt "$kexec_value_line" ]; then
    _pass "kexec value is outside TCP and directly under boot integrity"
else
    _fail "kexec value is outside TCP and directly under boot integrity"
fi

# --- rp_filter strict + mark-aware reverse-path lookup (M06 pair) -------
# wildcard *.rp_filter=1 added to override Fedora
# vendor /usr/lib/sysctl.d/50-default.conf wildcard *.rp_filter=2 (one-way
# ratchet semantics per kernel ip-sysctl docs).
assert_grep_extended '^net\.ipv4\.conf\.all\.rp_filter\s*=\s*1$'      "$TMPDIR/hardening.conf" "rp_filter=1 (all) — strict mode"
assert_grep_extended '^net\.ipv4\.conf\.default\.rp_filter\s*=\s*1$'  "$TMPDIR/hardening.conf" "rp_filter=1 (default) — strict mode"
assert_grep_extended '^net\.ipv4\.conf\.\*\.rp_filter\s*=\s*1$'       "$TMPDIR/hardening.conf" "rp_filter=1 (*) — wildcard override vs Fedora vendor 50-default.conf *=2"
assert_grep_extended '^net\.ipv4\.conf\.all\.src_valid_mark\s*=\s*1$' "$TMPDIR/hardening.conf" "src_valid_mark=1 (all) — mark participates in reverse lookup"
assert_grep_extended '^net\.ipv4\.conf\.default\.src_valid_mark\s*=\s*1$' "$TMPDIR/hardening.conf" "src_valid_mark=1 (default) — future-interface template"
assert_grep_fixed 'does not bypass validation' "$TMPDIR/hardening.conf" \
    "M02 records the kernel's mark-aware lookup semantics"
assert_not_grep_extended 'src_valid_mark.*(EXEMPTS|bypass)|fwmark.*bypasses rp_filter' \
    "$KS_FILE" "src_valid_mark is never misrepresented as an rp_filter exemption"

# --- 99-audit-fixes.conf content --------------------------------------------
assert_grep_extended '^kernel\.oops_limit\s*=\s*100$'  "$TMPDIR/audit-fixes.conf" "oops_limit=100"
assert_grep_extended '^kernel\.warn_limit\s*=\s*100$'  "$TMPDIR/audit-fixes.conf" "warn_limit=100"
assert_grep_extended '^kernel\.panic\s*=\s*-1$'        "$TMPDIR/audit-fixes.conf" "panic=-1"

# --- 99-userns.conf content -------------------------------------------------
assert_grep_extended '^user\.max_user_namespaces\s*=\s*256$' "$TMPDIR/userns.conf" "max_user_namespaces=256"

# --- binfmt_misc.status MUST be absent as ACTIVE sysctl key (comment OK) ----
# The header comment in hardening.conf references `fs.binfmt_misc.status` in the
# rationale block — that's expected. Only an actual `fs.binfmt_misc.status = ...`
# directive at the start of a line (no leading `#`) would be a regression.
if grep -qE '^fs\.binfmt_misc\.status[[:space:]]*=' "$TMPDIR/hardening.conf"; then
    _fail "regression: fs.binfmt_misc.status sysctl directive present"
else
    _pass "fs.binfmt_misc.status sysctl absent (M21 native unit masks authoritative)"
fi
if grep -qE '^fs\.binfmt_misc\.status[[:space:]]*=' "$TMPDIR/audit-fixes.conf"; then
    _fail "unexpected fs.binfmt_misc.status in audit-fixes.conf"
else
    _pass "audit-fixes.conf clean"
fi
if grep -qE '^fs\.binfmt_misc\.status[[:space:]]*=' "$TMPDIR/userns.conf"; then
    _fail "unexpected fs.binfmt_misc.status in userns.conf"
else
    _pass "userns.conf clean"
fi

# --- VPN-killswitch-compat: NO .all.disable_ipv6=1 --------------------------
assert_not_grep 'net\.ipv6\.conf\.all\.disable_ipv6' "$TMPDIR/hardening.conf"
assert_grep_extended '^net\.ipv6\.conf\.default\.disable_ipv6\s*=\s*1$' "$TMPDIR/hardening.conf" "default v6 off"
assert_not_grep 'VPN setup (Module 06) explicitly re-enables IPv6' "$KS_FILE" \
    "M02 does not attribute a nonexistent IPv6 action to M06"
assert_grep_fixed 'M07 and M23 own the physical-WAN disable' "$TMPDIR/hardening.conf" \
    "M02 names the actual physical-WAN IPv6 owners"
assert_grep_fixed 'VPN providers remain free to configure their own tunnel interfaces' \
    "$TMPDIR/hardening.conf" "M02 preserves provider-neutral tunnel ownership"

# --- ARP hardening triple pattern (all/default/wildcard) --------------------
for key in arp_ignore arp_announce drop_gratuitous_arp drop_unicast_in_l2_multicast; do
    assert_grep_extended "^net\\.ipv4\\.conf\\.all\\.${key}\\s*=" "$TMPDIR/hardening.conf" "ipv4.all.${key}"
    assert_grep_extended "^net\\.ipv4\\.conf\\.default\\.${key}\\s*=" "$TMPDIR/hardening.conf" "ipv4.default.${key}"
    assert_grep_extended "^net\\.ipv4\\.conf\\.\\*\\.${key}\\s*=" "$TMPDIR/hardening.conf" "ipv4.*.${key} wildcard"
done
for scope in all default '\*'; do
    assert_grep_extended "^net\\.ipv6\\.conf\\.${scope}\\.drop_unicast_in_l2_multicast\\s*=\\s*1$" \
        "$TMPDIR/hardening.conf" "IPv6 L2-multicast unicast drop (${scope})"
done

# --- KSPP 100% check (no nosmt, explicit cfi/lockdown absent) ---------------
# Hardening.conf has trailing inline comments (`# ...`) — allow whitespace
# or end-of-line after the numeric value.
assert_not_grep 'nosmt' "$KS_FILE"
assert_grep_extended '^kernel\.kptr_restrict\s*=\s*2([[:space:]]|$)' "$TMPDIR/hardening.conf" "kptr_restrict=2"
assert_grep_extended '^kernel\.unprivileged_bpf_disabled\s*=\s*1([[:space:]]|$)' "$TMPDIR/hardening.conf" "unprivileged_bpf=1 irreversible for running boot"
assert_grep_fixed '=2 — unprivileged bpf() disabled, but an administrator may later write' \
    "$TMPDIR/hardening.conf" "M02 records the kernel's reversible value-2 semantics"
assert_grep_fixed '=1 — unprivileged bpf() disabled without recovery' \
    "$TMPDIR/hardening.conf" "M02 records the kernel's irreversible value-1 semantics"
assert_not_grep_extended 'unprivileged_bpf_disabled=2 is STRICTER|=1.*runtime-resettable|=2.*MONOTONIC' \
    "$KS_FILE" "reversed BPF sysctl semantics cannot return"
assert_file_executable "$BPF_RUNTIME_GATE" \
    "three-pass unprivileged-BPF semantic gate is executable"
assert_file_executable "$SYSCTL_RUNTIME_GATE" \
    "three-pass complete M02 runtime gate is executable"
assert_grep_fixed 'case "$PASS_ID" in live|fresh-install|reboot)' \
    "$BPF_RUNTIME_GATE" "BPF gate has the exact lifecycle-pass set"
assert_grep_fixed 'sysctl -w "$SYSCTL=0"' "$BPF_RUNTIME_GATE" \
    "BPF gate probes the prohibited administrative reset"
assert_grep_fixed 'sysctl -w "$SYSCTL=1"' "$BPF_RUNTIME_GATE" \
    "unexpected weakening is immediately ratcheted back before failure"
assert_grep_fixed 'error == errno.EPERM' "$BPF_RUNTIME_GATE" \
    "BPF gate requires syscall-boundary EPERM for an unprivileged caller"
assert_grep_fixed 'installed M02 file contains an unbenchmarked performance override' \
    "$BPF_RUNTIME_GATE" "VM gate rejects image/source performance-policy drift"
assert_grep_fixed 'case "$PASS_ID" in live|fresh-install|reboot)' \
    "$SYSCTL_RUNTIME_GATE" "complete sysctl gate has the exact lifecycle-pass set"
assert_grep_fixed 'EXPECTED_DIRECTIVES = 105' "$SYSCTL_RUNTIME_GATE" \
    "complete sysctl gate pins every M02 directive"
assert_grep_fixed 'source/runtime mismatch' "$SYSCTL_RUNTIME_GATE" \
    "complete sysctl gate compares every concrete procfs value"
assert_grep_fixed 'byte-identical to its M02 heredoc' "$SYSCTL_RUNTIME_GATE" \
    "complete sysctl gate closes installed/source drift"
assert_grep_fixed 'Intentional NoID Privacy surface reduction (not a Fedora vendor default)' \
    "$TMPDIR/hardening.conf" "io_uring policy is not mislabeled as a Fedora default"
assert_grep_extended '^kernel\.io_uring_disabled\s*=\s*2$' \
    "$TMPDIR/hardening.conf" "io_uring is disabled for all callers"
assert_grep_fixed 'core_pattern would retain such text as' "$TMPDIR/hardening.conf" \
    "string-valued core_pattern remains protected from inline argument drift"

# --- 3 new sysctl params from Immutable cross-audit ---------
assert_grep_extended '^kernel\.printk\s*=\s*4 4 1 4$' "$TMPDIR/hardening.conf" "kernel.printk retains KERN_ERR while excluding warnings"
assert_grep_fixed 'numeric priority is LESS than' "$TMPDIR/hardening.conf" \
    "printk threshold semantics are documented precisely"
for scope in all default '\*'; do
    assert_grep_extended "^net\\.ipv4\\.conf\\.${scope}\\.shared_media\\s*=\\s*0$" "$TMPDIR/hardening.conf" "shared_media=0 (${scope})"
done

# --- 4 new sysctl params from Kicksecure security-misc audit ---
assert_grep_extended '^net\.ipv6\.icmp\.echo_ignore_all\s*=\s*1$' "$TMPDIR/hardening.conf" "IPv6 icmp.echo_ignore_all=1 (IPv4 parity)"
assert_not_grep 'ICMPv6-timestamp' "$KS_FILE" \
    "M02 does not invent nonexistent ICMPv6 timestamp messages"
for scope in all default '\*'; do
    assert_grep_extended "^net\\.ipv4\\.conf\\.${scope}\\.arp_filter\\s*=\\s*1$" "$TMPDIR/hardening.conf" "arp_filter=1 (${scope}) — anti-ARP-flux routing check"
done
assert_grep_fixed 'arp_ignore=1 answers only when the requested target address belongs' \
    "$TMPDIR/hardening.conf" "Mullvad audit attribution is attached to the correct control"

# --- no unbenchmarked generic-image performance profile --------------------
assert_not_grep_extended '^(net\.ipv4\.tcp_congestion_control|net\.core\.default_qdisc|net\.core\.(rmem_max|wmem_max|netdev_budget|netdev_max_backlog)|net\.ipv4\.tcp_(rmem|wmem|fastopen|mtu_probing|slow_start_after_idle)|vm\.(vfs_cache_pressure|dirty_bytes|dirty_background_bytes|max_map_count|page-cluster|swappiness))[[:space:]]*=' \
    "$TMPDIR/hardening.conf" "security module carries no unbenchmarked performance profile"
assert_grep_fixed 'A future NoID Privacy' "$TMPDIR/hardening.conf" \
    "future performance policy requires a separate measured opt-in surface"
assert_grep_fixed 'low/high-RAM, slow/fast-storage, no-VPN, WireGuard and OpenVPN measurements' \
    "$TMPDIR/hardening.conf" "required benchmark matrix is explicit"
assert_not_grep_extended 'Expected gain:|zero downside|zero security impact|right choice|negligible for single-client|high-RAM target|no cost during normal' \
    "$KS_FILE" "universal performance and zero-cost hype is absent"
assert_not_grep 'transient bit-flips into full panics' "$KS_FILE" \
    "M02 does not overstate the machine-check tolerance control"

# --- wildcard sweep (lo-inertness fix) ------
# follow-up to rp_filter: 5 latent INERT cases on lo
# interface confirmed by live-state inspection (lo created BEFORE
# sysctl.d loads, inherits kernel-defaults that .all=N cannot lower). Fix
# pattern: explicit `.*` wildcard alongside existing `.all` + `.default`.
# Plus 2 wildcards for accept_source_route triple-coverage consistency
# (vendor 50-default.conf already ships `*.accept_source_route=0` for IPv4
# matching NoID Privacy intent — no actual drift fixed, but pattern-completeness).
# src_valid_mark needs no wildcard: the kernel documents max(all, interface),
# while default retains the future-interface template.
assert_grep_extended '^net\.ipv4\.conf\.\*\.accept_redirects\s*=\s*0$'     "$TMPDIR/hardening.conf" "*.accept_redirects=0 — lo-inertness fix"
assert_grep_extended '^net\.ipv4\.conf\.\*\.secure_redirects\s*=\s*0$'     "$TMPDIR/hardening.conf" "*.secure_redirects=0 — lo-inertness fix"
assert_grep_extended '^net\.ipv6\.conf\.\*\.accept_redirects\s*=\s*0$'     "$TMPDIR/hardening.conf" "*.accept_redirects=0 IPv6 — lo-inertness fix"
assert_grep_extended '^net\.ipv4\.conf\.\*\.accept_source_route\s*=\s*0$'  "$TMPDIR/hardening.conf" "*.accept_source_route=0 — triple-coverage consistency"
assert_grep_extended '^net\.ipv6\.conf\.\*\.accept_source_route\s*=\s*0$'  "$TMPDIR/hardening.conf" "*.accept_source_route=0 IPv6 — triple-coverage consistency"
assert_grep_extended '^net\.ipv4\.conf\.\*\.send_redirects\s*=\s*0$'       "$TMPDIR/hardening.conf" "*.send_redirects=0 — lo-inertness fix"
assert_grep_extended '^net\.ipv4\.conf\.\*\.log_martians\s*=\s*1$'         "$TMPDIR/hardening.conf" "*.log_martians=1 — lo-inertness fix"

# --- complete runtime-gate functional fixture -------------------------------
runtime_sysctl="$TMPDIR/runtime-sysctl"
runtime_proc="$TMPDIR/runtime-proc"
mkdir -p "$runtime_sysctl" "$runtime_proc"
install -m 0640 "$TMPDIR/audit-fixes.conf" \
    "$runtime_sysctl/99-audit-fixes.conf"
install -m 0640 "$TMPDIR/hardening.conf" \
    "$runtime_sysctl/99-hardening.conf"
install -m 0640 "$TMPDIR/userns.conf" \
    "$runtime_sysctl/99-userns.conf"

python3 - "$runtime_proc" "$TMPDIR/audit-fixes.conf" \
    "$TMPDIR/hardening.conf" "$TMPDIR/userns.conf" <<'PY'
import re
import sys
from pathlib import Path

proc_root = Path(sys.argv[1])
for config_name in sys.argv[2:]:
    for raw_line in Path(config_name).read_text().splitlines():
        line = raw_line.strip()
        if not line or line.startswith("#"):
            continue
        match = re.fullmatch(r"-?([^=\s]+)\s*=\s*(.*?)\s*", line)
        if match is None:
            raise SystemExit(f"malformed fixture directive: {line}")
        key = match.group(1).replace("*", "test0")
        value = re.split(r"\s+#", match.group(2), maxsplit=1)[0]
        target = proc_root / key.replace(".", "/")
        target.parent.mkdir(parents=True, exist_ok=True)
        target.write_text(" ".join(value.split()) + "\n")
PY

runtime_gate_env=(
    env
    NOID_TEST_MODE=1
    NOID_TEST_KS_FILE="$KS_FILE"
    NOID_TEST_SYSCTL_ROOT="$runtime_sysctl"
    NOID_TEST_PROC_SYS_ROOT="$runtime_proc"
    NOID_TEST_EXPECT_UID="$(id -u)"
    NOID_TEST_EXPECT_GID="$(id -g)"
)
assert_cmd_success "complete M02 runtime fixture passes all source values" \
    "${runtime_gate_env[@]}" bash "$SYSCTL_RUNTIME_GATE" live
printf '3 3 3 3\n' > "$runtime_proc/kernel/printk"
assert_cmd_failure "complete M02 runtime fixture rejects one drifted value" \
    "${runtime_gate_env[@]}" bash "$SYSCTL_RUNTIME_GATE" live
printf '4 4 1 4\n' > "$runtime_proc/kernel/printk"
chmod 0644 "$runtime_sysctl/99-userns.conf"
assert_cmd_failure "complete M02 runtime fixture rejects weak file metadata" \
    "${runtime_gate_env[@]}" bash "$SYSCTL_RUNTIME_GATE" live

test_finish
