#!/bin/bash
# NoID Privacy Workstation — shared test helper library
#
# Sourced by each tests/NN-*.sh file. Provides minimal assertion helpers,
# colored output, and test-run accounting. Kept intentionally tiny so the
# tests themselves stay readable (no DSL, no magic).
#
# Usage:
#   #!/bin/bash
#   set -euo pipefail
#   . "$(dirname "$0")/lib.sh"
#   test_start "My test name"
#
#   assert_file_exists /some/path
#   assert_grep "pattern" /some/file
#   assert_eq "expected" "actual"
#
#   test_finish   # prints summary, exits non-zero on any failure

# No test may leave generated bytecode in the source surface. Several tests
# import repository Python by path, and an import -- unlike running a script --
# writes __pycache__ next to the imported file. The canonical PII sweep refuses
# a source tree carrying one, so a run that produced it made the NEXT run fail
# with a finding that had nothing to do with the change under test. Individual
# fixtures already set sys.dont_write_bytecode; setting it for every child
# process here closes the class instead of chasing each importer.
export PYTHONDONTWRITEBYTECODE=1
export LC_ALL=C.UTF-8

# Production helpers intentionally journal failures. Behavioral fixtures also
# exercise those failure paths, but their evidence must never be
# indistinguishable from a real host incident. Every test sourcing this
# library exports a Bash `logger` shim to child scripts; it preserves the real
# logger transport while suffixing an explicit tag with `-test`.
logger() {
    local arg
    local expect_tag=0
    local saw_tag=0
    local tag
    local -a rewritten=()

    for arg in "$@"; do
        if [ "$expect_tag" -eq 1 ]; then
            case "$arg" in
                *-test) rewritten+=("$arg") ;;
                *) rewritten+=("${arg}-test") ;;
            esac
            saw_tag=1
            expect_tag=0
            continue
        fi
        case "$arg" in
            -t|--tag)
                rewritten+=("$arg")
                expect_tag=1
                ;;
            --tag=*)
                tag=${arg#--tag=}
                case "$tag" in
                    *-test) rewritten+=("$arg") ;;
                    *) rewritten+=("--tag=${tag}-test") ;;
                esac
                saw_tag=1
                ;;
            *)
                rewritten+=("$arg")
                ;;
        esac
    done
    [ "$expect_tag" -eq 0 ] || {
        printf '%s\n' "test logger shim: missing tag value" >&2
        return 2
    }
    if [ "$saw_tag" -eq 0 ]; then
        rewritten=(-t noid-test "${rewritten[@]}")
    fi
    "${NOID_TEST_LOGGER_BACKEND:-/usr/bin/logger}" "${rewritten[@]}"
}
export -f logger
export NOID_TEST_RUN=1

# --- state (per-file) -------------------------------------------------------

TEST_NAME=""
TEST_CHECKS=0
TEST_FAILS=0
TEST_SKIPS=0
TEST_FIRST_FAIL_MSG=""

# --- output helpers ---------------------------------------------------------

if [ -t 1 ]; then
    C_OK=$'\033[32m'
    C_FAIL=$'\033[31m'
    C_DIM=$'\033[2m'
    C_RST=$'\033[0m'
else
    C_OK=""; C_FAIL=""; C_DIM=""; C_RST=""
fi

test_start() {
    TEST_NAME="$1"
    TEST_CHECKS=0
    TEST_FAILS=0
    TEST_SKIPS=0
    TEST_FIRST_FAIL_MSG=""
    printf '%s\n' "=== $TEST_NAME ==="
}

test_finish() {
    local total="$TEST_CHECKS"
    local failed="$TEST_FAILS"
    local passed=$((total - failed))
    local skipped=""
    [ "$TEST_SKIPS" -eq 0 ] || skipped=", $TEST_SKIPS skipped"
    # A file that neither checked nor explicitly skipped anything proved
    # nothing; report it as a failure instead of an empty PASS.
    if [ "$total" -eq 0 ] && [ "$TEST_SKIPS" -eq 0 ]; then
        printf '%sFAIL%s  %s  (no check executed)\n' "$C_FAIL" "$C_RST" "$TEST_NAME"
        return 1
    fi
    if [ "$failed" -eq 0 ]; then
        printf '%sPASS%s  %s  (%d checks%s)\n' "$C_OK" "$C_RST" "$TEST_NAME" "$total" "$skipped"
        return 0
    else
        printf '%sFAIL%s  %s  (%d/%d checks passed%s)\n' "$C_FAIL" "$C_RST" "$TEST_NAME" "$passed" "$total" "$skipped"
        [ -n "$TEST_FIRST_FAIL_MSG" ] && printf '%s  first-fail: %s%s\n' "$C_DIM" "$TEST_FIRST_FAIL_MSG" "$C_RST"
        return 1
    fi
}

_pass() {
    TEST_CHECKS=$((TEST_CHECKS + 1))
    printf '  %s[OK]%s %s\n' "$C_OK" "$C_RST" "$1"
}

_fail() {
    TEST_CHECKS=$((TEST_CHECKS + 1))
    TEST_FAILS=$((TEST_FAILS + 1))
    [ -z "$TEST_FIRST_FAIL_MSG" ] && TEST_FIRST_FAIL_MSG="$1"
    printf '  %s[FAIL]%s %s\n' "$C_FAIL" "$C_RST" "$1"
}

# A check whose required host capability is unavailable is reported as SKIP:
# it is neither counted as a passed check nor as a failure. The "[SKIP]" line
# is the marker tests/run-all.sh counts as a capability skip event.
_skip() {
    TEST_SKIPS=$((TEST_SKIPS + 1))
    printf '  %s[SKIP]%s %s\n' "$C_DIM" "$C_RST" "$1"
}

# --- assertions -------------------------------------------------------------

assert_file_exists() {
    local path="$1"
    local desc="${2:-file exists: $path}"
    if [ -f "$path" ]; then
        _pass "$desc"
    else
        _fail "$desc"
    fi
}

assert_file_executable() {
    local path="$1"
    local desc="${2:-executable: $path}"
    if [ -x "$path" ]; then
        _pass "$desc"
    else
        _fail "$desc"
    fi
}

assert_file_min_size() {
    local path="$1"
    local min="$2"
    local desc="${3:-size(${path}) >= ${min}}"
    if [ -f "$path" ]; then
        local sz
        sz=$(stat -c %s "$path" 2>/dev/null || echo 0)
        sz=${sz:-0}
        if [ "$sz" -ge "$min" ]; then
            _pass "$desc (actual: $sz)"
        else
            _fail "$desc (actual: $sz)"
        fi
    else
        _fail "$desc (file missing)"
    fi
}

assert_grep() {
    local pattern="$1"
    local path="$2"
    local desc="${3:-grep '$pattern' $path}"
    if grep -q -- "$pattern" "$path" 2>/dev/null; then
        _pass "$desc"
    else
        _fail "$desc"
    fi
}

assert_grep_extended() {
    local pattern="$1"
    local path="$2"
    local desc="${3:-grep -E '$pattern' $path}"
    if grep -qE -- "$pattern" "$path" 2>/dev/null; then
        _pass "$desc"
    else
        _fail "$desc"
    fi
}

assert_grep_fixed() {
    local pattern="$1"
    local path="$2"
    local desc="${3:-grep -F '$pattern' $path}"
    if grep -qF -- "$pattern" "$path" 2>/dev/null; then
        _pass "$desc"
    else
        _fail "$desc"
    fi
}

assert_not_grep() {
    local pattern="$1"
    local path="$2"
    local desc="${3:-!grep '$pattern' $path}"
    local grep_status
    # Readable, not necessarily a regular file. The guard exists because a
    # missing target used to pass a negative assertion silently — grep on a
    # nonexistent path exits non-zero, which reads as "pattern absent". But
    # requiring `-f` also rejects the process substitutions several callers
    # legitimately use to assert on captured output: `<(...)` is a pipe, so
    # every one of those assertions failed unconditionally. `-r` alone keeps
    # the fail-closed behaviour — it is false for a path that does not exist.
    if [ ! -r "$path" ]; then
        _fail "$desc (target missing or unreadable)"
        return
    fi
    if grep -q -- "$pattern" "$path" 2>/dev/null; then
        grep_status=0
    else
        grep_status=$?
    fi
    case "$grep_status" in
        0) _fail "$desc" ;;
        1) _pass "$desc" ;;
        *) _fail "$desc (grep failed with status $grep_status)" ;;
    esac
}

assert_not_grep_fixed() {
    local pattern="$1"
    local path="$2"
    local desc="${3:-!grep -F '$pattern' $path}"
    local grep_status
    # Readable, not necessarily a regular file. The guard exists because a
    # missing target used to pass a negative assertion silently — grep on a
    # nonexistent path exits non-zero, which reads as "pattern absent". But
    # requiring `-f` also rejects the process substitutions several callers
    # legitimately use to assert on captured output: `<(...)` is a pipe, so
    # every one of those assertions failed unconditionally. `-r` alone keeps
    # the fail-closed behaviour — it is false for a path that does not exist.
    if [ ! -r "$path" ]; then
        _fail "$desc (target missing or unreadable)"
        return
    fi
    if grep -qF -- "$pattern" "$path" 2>/dev/null; then
        grep_status=0
    else
        grep_status=$?
    fi
    case "$grep_status" in
        0) _fail "$desc" ;;
        1) _pass "$desc" ;;
        *) _fail "$desc (grep failed with status $grep_status)" ;;
    esac
}

assert_not_grep_extended() {
    local pattern="$1"
    local path="$2"
    local desc="${3:-!grep -E '$pattern' $path}"
    local grep_status
    # Readable, not necessarily a regular file. The guard exists because a
    # missing target used to pass a negative assertion silently — grep on a
    # nonexistent path exits non-zero, which reads as "pattern absent". But
    # requiring `-f` also rejects the process substitutions several callers
    # legitimately use to assert on captured output: `<(...)` is a pipe, so
    # every one of those assertions failed unconditionally. `-r` alone keeps
    # the fail-closed behaviour — it is false for a path that does not exist.
    if [ ! -r "$path" ]; then
        _fail "$desc (target missing or unreadable)"
        return
    fi
    if grep -qE -- "$pattern" "$path" 2>/dev/null; then
        grep_status=0
    else
        grep_status=$?
    fi
    case "$grep_status" in
        0) _fail "$desc" ;;
        1) _pass "$desc" ;;
        *) _fail "$desc (grep failed with status $grep_status)" ;;
    esac
}

assert_eq() {
    local want="$1"
    local got="$2"
    local desc="${3:-eq}"
    if [ "$want" = "$got" ]; then
        _pass "$desc"
    else
        _fail "$desc  want='$want'  got='$got'"
    fi
}

assert_cmd_success() {
    local desc="$1"; shift
    if "$@" >/dev/null 2>&1; then
        _pass "$desc"
    else
        _fail "$desc"
    fi
}

assert_cmd_failure() {
    local desc="$1" rc=0; shift
    # A missing, mistyped or non-executable command also exits non-zero. That
    # is a broken test, not the rejection this assertion claims to observe.
    if ! command -v -- "$1" >/dev/null 2>&1; then
        _fail "$desc (command not found or not executable: $1)"
        return
    fi
    "$@" >/dev/null 2>&1 || rc=$?
    case "$rc" in
        0) _fail "$desc" ;;
        126|127) _fail "$desc (command could not be executed, rc=$rc)" ;;
        *) _pass "$desc" ;;
    esac
}

# Assert an exact exit status where the program under test documents one.
# Usage: assert_cmd_status <expected-rc> <desc> <cmd> [args...]
assert_cmd_status() {
    local want="$1" desc="$2" rc=0
    shift 2
    if ! command -v -- "$1" >/dev/null 2>&1; then
        _fail "$desc (command not found or not executable: $1)"
        return
    fi
    "$@" >/dev/null 2>&1 || rc=$?
    if [ "$rc" -eq "$want" ]; then
        _pass "$desc"
    else
        _fail "$desc  want rc=$want  got rc=$rc"
    fi
}

# --- heredoc extraction ------------------------------------------------------
#
# Extract one heredoc body from a kickstart snippet (or any shell file) into a
# target file.
# Usage: extract_heredoc <ks-file> <heredoc-marker> <target-file> [occurrence]
# Example: extract_heredoc kickstart/snippets/29-user-docs.ks README_EOF /tmp/README.md
#
# Only the Nth block opened with <marker> is written (default: the first).
# A missing occurrence, an unterminated block or an empty body is a failure,
# so a truncated or duplicated payload can never pass as one intact heredoc.

extract_heredoc() {
    local ks_file="$1"
    local marker="$2"
    local target="$3"
    local occurrence="${4:-1}"
    awk -v m="$marker" -v want="$occurrence" '
        # Match the complete token after << (optionally quoted / <<-), not a
        # suffix: SVC_EOF must not also match SCRUB_SVC_EOF.
        BEGIN { opener = "<<-?[[:space:]]*[\047\"]?" m "[\047\"]?([[:space:]]|$)" }
        state == 0 && $0 ~ opener {
            seen++
            state = (seen == want) ? 1 : 2
            next
        }
        state && ($0 == m || $0 ~ "^[\\t]+" m "$") {
            if (state == 1) { closed = 1; exit }
            state = 0
            next
        }
        state == 1 { print }
        END { if (!closed) exit 1 }
    ' "$ks_file" > "$target" || return 1
    # An empty body is an extraction failure as well.
    [ -s "$target" ]
}

# --- scratch directories -----------------------------------------------------
#
# Create a private scratch directory in which fixture programs may execute.
# /tmp is mounted noexec on the hardened development host and a checkout must
# never hold scratch trees (a concurrent `git add -A` would commit them and the
# PII sweep scans the whole checkout), so the default parent is the
# disk-backed, exec-capable /var/tmp. NOID_TEST_EXEC_TMPDIR selects another
# parent. The caller owns cleanup (normally an EXIT trap).
# Usage: dir=$(make_exec_tmpdir <label>)
make_exec_tmpdir() {
    local label="${1:?make_exec_tmpdir: label required}"
    local parent="${NOID_TEST_EXEC_TMPDIR:-/var/tmp}"
    local dir
    dir=$(mktemp -d "$parent/noid-test-$label.XXXXXX") || return 1
    if ! printf '#!/bin/sh\nexit 0\n' > "$dir/.exec-probe" \
            || ! chmod 0700 "$dir/.exec-probe" \
            || ! "$dir/.exec-probe" 2>/dev/null \
            || ! rm -f -- "$dir/.exec-probe"; then
        rm -rf -- "$dir"
        printf '%s\n' "ERROR: $parent does not permit executing test fixtures; set NOID_TEST_EXEC_TMPDIR" >&2
        return 1
    fi
    printf '%s\n' "$dir"
}

# --- project root detection --------------------------------------------------

# Resolve project root from the test-script location. Tests live under
# tests/, so project root is one directory up.
#
# Usage at top of test:
#   PROJECT_ROOT="$(find_project_root)"
find_project_root() {
    # dirname of BASH_SOURCE[1] = caller's dir (tests/), parent = project root
    local caller_dir
    caller_dir="$(cd "$(dirname "${BASH_SOURCE[1]}")" && pwd)"
    if [ -f "$caller_dir/../kickstart/master.ks" ]; then
        (cd "$caller_dir/.." && pwd)
    elif [ -f "$caller_dir/kickstart/master.ks" ]; then
        # Called from project root (not from tests/)
        echo "$caller_dir"
    else
        echo "ERROR: cannot find project root from $caller_dir" >&2
        return 1
    fi
}
