#!/bin/bash
# NoID Privacy Workstation — run all pre-LOCK semantic tests
#
# Runs every tests/NN-*.sh in numeric order, reports pass/fail per test,
# exits non-zero if any test fails. Intended to be run before marking
# a Module or image-cut `LOCKED` (see CONTRIBUTING.md gate).
#
# Usage:
#   ./tests/run-all.sh            # all tests
#   ./tests/run-all.sh 22 29      # only tests matching "22" or "29"
#   ./tests/run-all.sh --verbose  # show per-check lines even on pass
#
# Exit codes:
#   0  all tests passed
#   1  one or more tests failed
#   2  test-harness error (couldn't find tests, couldn't source lib)

set -uo pipefail
export LC_ALL=C.UTF-8

# Belt and braces with tests/lib.sh: no run may leave generated bytecode
# in the source surface, or the next run fails the canonical PII sweep on a
# finding unrelated to the change under test.
export PYTHONDONTWRITEBYTECODE=1

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
PROJECT_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"

if [ ! -f "$SCRIPT_DIR/lib.sh" ]; then
    echo "ERROR: $SCRIPT_DIR/lib.sh not found" >&2
    exit 2
fi

# --- parse args -------------------------------------------------------------

VERBOSE=0
FILTERS=()

for arg in "$@"; do
    case "$arg" in
        --verbose|-v) VERBOSE=1 ;;
        --help|-h)
            awk 'NR == 1 { next } /^$/ { exit } { sub(/^# ?/, ""); print }' "$0"
            exit 0
            ;;
        -*)
            echo "run-all.sh: unknown flag '$arg'" >&2
            exit 2
            ;;
        *)
            FILTERS+=("$arg")
            ;;
    esac
done

# --- discover tests ---------------------------------------------------------

# Discovery glob accepts NN-*.sh AND NN<letter>-*.sh (e.g. 13b-noid-status-
# structural.sh — companion test paired with main NN-*.sh, matches the
# kickstart-snippet naming convention used for 11b-dns-health.ks).
mapfile -t ALL_TESTS < <(find "$SCRIPT_DIR" -maxdepth 1 -type f -name '[0-9][0-9]*-*.sh' -print 2>/dev/null | sort)

if [ "${#ALL_TESTS[@]}" -eq 0 ]; then
    echo "ERROR: no tests found under $SCRIPT_DIR (expected NN-*.sh)" >&2
    exit 2
fi

# Apply filters if any
if [ "${#FILTERS[@]}" -gt 0 ]; then
    SELECTED=()
    for t in "${ALL_TESTS[@]}"; do
        base=$(basename "$t")
        for f in "${FILTERS[@]}"; do
            if [[ "$base" == *"$f"* ]]; then
                SELECTED+=("$t")
                break
            fi
        done
    done
    ALL_TESTS=("${SELECTED[@]}")
fi

if [ "${#ALL_TESTS[@]}" -eq 0 ]; then
    echo "ERROR: no tests match filters: ${FILTERS[*]}" >&2
    exit 2
fi

# A complete release-gate run is one reproducible contract, not a best-effort
# capability sweep. Several module tests exercise extracted helpers with
# ShellCheck, the Kickstart gates require ksvalidator, and M40 validates an
# exact sibling Git checkout plus its patch fixture. Fail once, before any
# partial result can be mistaken for source regressions. Filtered developer
# runs retain each selected test's own dependency/capability behavior.
if [ "${#FILTERS[@]}" -eq 0 ]; then
    missing_tools=()
    for tool in aide base64 bwrap checkmodule clang dconf \
                desktop-file-validate git gsettings jq ksvalidator patch \
                python3 semodule_package sha256sum setfacl shellcheck strip \
                systemd-analyze systemd-tmpfiles udevadm \
                usbguard usbguard-notifier visudo; do
        command -v "$tool" >/dev/null 2>&1 || missing_tools+=("$tool")
    done
    if command -v python3 >/dev/null 2>&1 \
       && ! python3 -c 'import auparse' >/dev/null 2>&1; then
        missing_tools+=("python3:auparse")
    fi
    [ -r /usr/include/bpf/bpf_helpers.h ] \
        || missing_tools+=("libbpf-devel:bpf_helpers.h")
    [ -r /usr/include/linux/bpf.h ] \
        || missing_tools+=("kernel-headers:linux/bpf.h")
    if [ "${#missing_tools[@]}" -ne 0 ]; then
        printf 'ERROR: full-suite prerequisites missing:' >&2
        printf ' %s' "${missing_tools[@]}" >&2
        printf '\nFedora: sudo dnf install ShellCheck aide acl binutils bubblewrap checkpolicy clang dconf desktop-file-utils git glib2 gvfs jq kernel-headers libbpf-devel patch policycoreutils pykickstart python3 python3-audit sudo systemd systemd-udev usbguard usbguard-notifier\n' >&2
        exit 2
    fi
    missing_schemas=()
    for schema in org.gnome.system.wsdd org.gnome.system.dns_sd; do
        gsettings list-schemas | grep -qxF "$schema" \
            || missing_schemas+=("$schema")
    done
    if [ "${#missing_schemas[@]}" -ne 0 ]; then
        printf 'ERROR: full-suite GSettings schemas missing:' >&2
        printf ' %s' "${missing_schemas[@]}" >&2
        printf '\nFedora: sudo dnf install gvfs\n' >&2
        exit 2
    fi
fi

# --- run tests --------------------------------------------------------------

if [ -t 1 ]; then
    C_OK=$'\033[32m'
    C_FAIL=$'\033[31m'
    C_BOLD=$'\033[1m'
    C_DIM=$'\033[2m'
    C_RST=$'\033[0m'
else
    C_OK=""; C_FAIL=""; C_BOLD=""; C_DIM=""; C_RST=""
fi

total=0
passed=0
failed=0
skip_events=0
skipped_tests=0
failed_names=()

START_TS=$SECONDS
for t in "${ALL_TESTS[@]}"; do
    total=$((total + 1))
    name=$(basename "$t" .sh)

    if [ "$VERBOSE" -eq 1 ]; then
        if (cd "$PROJECT_ROOT" && bash "$t"); then
            passed=$((passed + 1))
        else
            failed=$((failed + 1))
            failed_names+=("$name")
        fi
    else
        # Capture output, show only on failure
        out=$( (cd "$PROJECT_ROOT" && bash "$t") 2>&1 ) ; rc=$?
        test_skip_events=$(printf '%s\n' "$out" \
            | grep -cE '^[[:space:]]*\[SKIP\]' || true)
        test_skip_events=${test_skip_events:-0}
        if [ "$test_skip_events" -gt 0 ]; then
            skip_events=$((skip_events + test_skip_events))
            skipped_tests=$((skipped_tests + 1))
        fi
        if [ "$rc" -eq 0 ]; then
            passed=$((passed + 1))
            if [ "$test_skip_events" -gt 0 ]; then
                printf '%sPASS%s  %s  (%d capability skip event(s))\n' \
                    "$C_OK" "$C_RST" "$name" "$test_skip_events"
            else
                printf '%sPASS%s  %s\n' "$C_OK" "$C_RST" "$name"
            fi
        else
            failed=$((failed + 1))
            failed_names+=("$name")
            printf '%sFAIL%s  %s\n' "$C_FAIL" "$C_RST" "$name"
            printf '%s%s%s\n' "$C_DIM" "$out" "$C_RST" | sed 's/^/  | /'
        fi
    fi
done
ELAPSED=$((SECONDS - START_TS))

# --- summary ----------------------------------------------------------------

echo ""
echo "--------------------------------------------------------------------"
if [ "$failed" -eq 0 ]; then
    printf '%sAll tests passed%s: %d/%d  (%ds)\n' "$C_BOLD$C_OK" "$C_RST" "$passed" "$total" "$ELAPSED"
    if [ "$skip_events" -gt 0 ]; then
        printf 'Capability skips surfaced: %d event(s) across %d test(s).\n' \
            "$skip_events" "$skipped_tests"
    fi
    # Hint: bwrap smoke tests are opt-in (need root + rootfs)
    if [ -d "$SCRIPT_DIR/smoke" ] && [ "${SKIP_SMOKE_HINT:-0}" != "1" ]; then
        printf '\n%sBwrap smoke tests available%s: %ssudo ./tests/smoke/run-all.sh%s (requires bubblewrap + prepared rootfs)\n' \
            "$C_DIM" "$C_RST" "$C_BOLD" "$C_RST"
    fi
    exit 0
else
    printf '%sTests FAILED%s: %d/%d passed, %d failed  (%ds)\n' "$C_BOLD$C_FAIL" "$C_RST" "$passed" "$total" "$failed" "$ELAPSED"
    printf 'Failures:\n'
    for n in "${failed_names[@]}"; do
        printf '  - %s\n' "$n"
    done
    exit 1
fi
