#!/usr/bin/env bash
# Regenerate branding/SHA256SUMS through the shared fail-before-write contract.
set -euo pipefail

REPO_ROOT="$(cd "$(dirname "$0")/.." && pwd)"
LIB="$REPO_ROOT/scripts/lib/source-generator.sh"
# shellcheck source=scripts/lib/source-generator.sh
. "$LIB"
BRANDING_DIR=${NOID_BRANDING_DIR:-$REPO_ROOT/branding}
MANIFEST=${NOID_BRANDING_MANIFEST:-$BRANDING_DIR/SHA256SUMS}

log() { echo "[regen-branding-shasums] $*"; }
usage() { echo "Usage: scripts/regen-branding-shasums.sh [--check]"; }
noid_generator_parse_cli "$@" || { usage >&2; exit 2; }
[ "$NOID_GENERATOR_MODE" != help ] || { usage; exit 0; }
noid_generator_require_tools cmp cut find grep mktemp mv readlink sha256sum \
    sort stat || exit 2
[ -d "$BRANDING_DIR" ] && [ ! -L "$BRANDING_DIR" ] \
    || { log "ERROR: branding root is missing or symlinked"; exit 2; }
BRANDING_DIR=$(readlink -e -- "$BRANDING_DIR")
[ "${MANIFEST%/*}" = "$BRANDING_DIR" ] \
    || { log "ERROR: manifest must be a direct branding-root child"; exit 2; }
noid_generator_require_file "$MANIFEST" || exit 2
if find "$BRANDING_DIR" -type l -print -quit | grep -q .; then
    log "ERROR: branding payload must not contain symlinks"
    exit 3
fi

mapfile -d '' files < <(
    cd "$BRANDING_DIR"
    find . -type f ! -name SHA256SUMS ! -name '*.sh' \
        ! -path '*/.bak-*/*' -print0 | LC_ALL=C sort -z
)
[ "${#files[@]}" -gt 0 ] || { log "ERROR: no branding assets found"; exit 3; }
for file in "${files[@]}"; do
    [[ $file != *$'\n'* ]] || { log "ERROR: newline in branding filename"; exit 3; }
done

candidate=$(noid_generator_temp_for "$MANIFEST") || exit 4
trap 'rm -f -- "$candidate"' EXIT HUP INT TERM
{
    echo "# NoID Privacy Workstation — branding asset SHA256 manifest"
    echo "# Generated by scripts/regen-branding-shasums.sh"
    echo "# Re-run after editing any file under branding/ (excluding .bak-* and *.sh)."
    echo "# Module 32 (kickstart/snippets/32-branding.ks) verifies each HTTP-fetched"
    echo "# asset against this manifest before installing into the image."
    echo "#"
    (
        cd "$BRANDING_DIR"
        for file in "${files[@]}"; do
            sha256sum -- "${file#./}"
        done
    )
} > "$candidate"

data_count=$(grep -cvE '^[[:space:]]*(#|$)' "$candidate")
[ "$data_count" -eq "${#files[@]}" ] \
    || { log "ERROR: generated manifest count drifted"; exit 4; }
(
    cd "$BRANDING_DIR"
    sha256sum --check --strict --status "$candidate"
) || { log "ERROR: generated manifest failed content verification"; exit 4; }

if cmp -s "$candidate" "$MANIFEST"; then
    log "IN SYNC: manifest matches ${#files[@]} branding assets"
    exit 0
fi
[ "$NOID_GENERATOR_MODE" != check ] \
    || { log "DRIFT DETECTED: run scripts/regen-branding-shasums.sh"; exit 1; }
noid_generator_publish "$candidate" "$MANIFEST" || exit 4
candidate=''
trap - EXIT HUP INT TERM
log "OK: branding manifest verified and published atomically"
